import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,makePlayer,clone} from '../public/js/engine.js';
import {CARD,CARDS} from '../public/js/cards.js';
import {random} from '../scripts/adaptive-strategies.mjs';
import {visible} from '../scripts/strategic-timing.mjs';
import {retentionOrder,freshMemory,rolloutRetention,aggregateRetention,expectedIncome,HIGH} from '../scripts/high-cost-retention.mjs';
function simple(){const p=makePlayer('0','0');p.hand=['dwarf_beer','human_smith','goblin_junk','elf_marchant','human_knight'];const q=makePlayer('1','1');return {p,q,s:{case:'pair',targets:['dwarf_beer','human_smith']},settings:{warVP:[4,0],additionalObjectives:false}};}
test('initial interventions alter only target discard choices, and retain exactly one target copy',()=>{const {p,q,s,settings}=simple(),before=clone(p),order=k=>retentionOrder(s,k,p,[q],settings,1,freshMemory()),a=order('once'),b=order('drop'),c=order('beerOnce');assert.ok(!a.discard.includes(0)&&!a.discard.includes(1));assert.ok(b.discard.includes(0)&&b.discard.includes(1));assert.ok(!c.discard.includes(0)&&c.discard.includes(1));assert.deepEqual(a.discard.filter(i=>i>1),b.discard.filter(i=>i>1));assert.deepEqual(p,before);p.hand[4]='dwarf_beer';const d=order('once');assert.ok(!d.discard.includes(0)&&d.discard.includes(4));});
test('locked holding survives funding shortages, while release rules discard only pending targets',()=>{const {p,q,s,settings}=simple();p.gold=1;const m=freshMemory();assert.ok(!retentionOrder(s,'locked',p,[q],settings,3,m).discard.includes(0));const n=freshMemory();n.placedAt.human_smith=1;const d=retentionOrder(s,'round2',p,[q],settings,3,n);assert.ok(d.discard.includes(0));assert.deepEqual(n.released,['dwarf_beer']);const f=freshMemory();p.gold=5;const o=retentionOrder(s,'affordable',p,[q],settings,2,f);assert.ok(o.discard.includes(0)&&!o.discard.includes(1));});
test('budget forecast uses development before income and does not borrow future hand cards',()=>{const p=makePlayer('0','0');p.tech=2;p.board=[{card:'dwarf_cook',x:0,y:0},{card:'dwarf_gem',x:1,y:0}];assert.equal(expectedIncome(p),2);p.hand=['demon_eye','golem_stollow'];assert.equal(expectedIncome(p),2);assert.equal(p.tech,2);});
test('natural-deal continuations end legally and never use the opponent actual hand',()=>{let g;for(let seed=1;seed<1000;seed++){g=newGame([{id:'0',name:'0'},{id:'1',name:'1'}],{},random(seed));if(g.players[0].hand.some(id=>HIGH.includes(id)))break;}const target=g.players[0].hand.find(id=>HIGH.includes(id)),s={case:'single',targets:[target],p:clone(g.players[0]),opponents:[visible(g.players[1])],settings:g.settings,discard:[],phase:'draw',round:1};const a=rolloutRetention(s,'locked','balanced',100);assert.ok(a.ended);assert.equal(a.lastRound,a.trajectory.at(-1).round);assert.equal(a.vp,a.trajectory.at(-1).vp);s.opponents[0].hand=Array(5).fill('demon_storm');assert.deepEqual(rolloutRetention(s,'locked','balanced',100),a);assert.equal(CARDS.reduce((n,c)=>n+c.copies,0),102);});
test('uncompleted simulations are not silently turned into defeats',()=>{const r={ended:false,share:null,vp:null,gap:null,lastRound:12,completedAt:null,placedAt:{},returnedAt:{},releaseEvents:[],targetVP:0,cardIncome:0,drawn:0,unaffordable:1,unplaced:['dwarf_beer']};const d=aggregateRetention([r],{targets:['dwarf_beer']});assert.equal(d.ended,0);assert.equal(d.share,null);assert.equal(d.neverPlaced,1);});
test('focused-placement sensitivity has exactly the same outcomes when emphasis is balanced',async()=>{const {rolloutFocused,focusRoute}=await import('../scripts/focused-high-cost-retention.mjs');const g=newGame([{id:'0',name:'0'},{id:'1',name:'1'}],{},random(123));const s={case:'single',targets:[g.players[0].hand[0]],p:clone(g.players[0]),opponents:[visible(g.players[1])],settings:g.settings,discard:[],phase:'draw',round:1};assert.deepEqual(rolloutFocused(s,'locked','balanced',100,{strategy:'balanced'}),rolloutRetention(s,'locked','balanced',100));assert.equal(focusRoute({targets:['human_king']}),'savings');assert.equal(focusRoute({targets:['dwarf_beer','human_smith']}),'tech');});
